### ISSUE TITLE
generated captions

### ISSUE THREAD

**Issue by jayleicn** [jamespark3922/adv-inf#1]
Hi @jamespark3922,

Could you share the generated captions of the models used in the paper? Including the ones from references [13, 76, 67].

Best,
Jie

**Comment by jayleicn** [comment]
Also, the file `para_1.json`  and `para_2.json` are missing for the repo https://github.com/jamespark3922/densevid_eval.

**Comment by jamespark3922** [comment]
Thanks for pointing out the missing files!
added the json files under `data` in `densevid_eval`.
