### ISSUE TITLE
Gan.

### ISSUE THREAD

**Issue by pananiko** [jamespark3922/adv-inf#3]
Hi @jamespark3922 ,

Are you considering  to release  the code  for training it as GAN?  It will be a very interesting  code base, and will be very complementary  to Luo's. In case you don't  plan to release  it maybe you could share it with me via e-mail?

Regards,
panos

**Comment by jamespark3922** [comment]
I'm not planning on releasing the code for GAN training, but it should be almost the same in Luo's code, but just replacing cider reward with discriminator reward. I have the discriminator reward function `get_self_critical_reward_video` in `misc/utils.py`, which corresponds to Luo's `get_self_critical_reward` in `misc/loss_wrapper.py`.
